apiVersion: v1
kind: Namespace
metadata:
  name: careforall
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: careforall
type: Opaque
stringData:
  # In production, use sealed secrets or a vault
  POSTGRES_PASSWORD: "secure_password_123"
  GRAFANA_ADMIN_PASSWORD: "admin"
  JWT_SECRET: fat32_super_secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: careforall
data:
  ENVIRONMENT: "production"
  POSTGRES_USER: "postgres"
  # Service Discovery URLs
  USER_SERVICE_URL: "http://user-service:8001"
  CAMPAIGN_SERVICE_URL: "http://campaign-service:8002"
  DONATION_SERVICE_URL: "http://donation-service:8004"
  PAYMENT_SERVICE_URL: "http://payment-service:8003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8005"
  BANKING_SERVICE_URL: "http://banking-service:8006"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  ZOOKEEPER_CONNECT: "zookeeper:2181"
  REDIS_HOST: "redis"

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJrZGJheml6dWwiLCJwYXNzd29yZCI6IkxvdmVnYW1lczIiLCJlbWFpbCI6ImtkYmF6aXp1bEBnbWFpbC5jb20iLCJhdXRoIjoiYTJSaVlYcHBlblZzT2t4dmRtVm5ZVzFsY3pJPSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: careforall
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: careforall
imagePullSecrets:
- name: regcred
